displayName: Test Plugin for kubernates for correlationId
type: middleware

import: github.com/killer-djon/traefik-correlation

summary: 'Traefik plugin to catch correlationId from header'

testData:
  headerName: "correlation-id"